USE codeup_test_db;

DROP TABLE IF EXISTS albums;

CREATE TABLE albums (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	artist VARCHAR(50) NOT NULL,
	name VARCHAR(100) DEFAULT 'NONE',
	release_date DATE,
	sales INT UNSIGNED,
	genre VARCHAR(100) DEFAULT 'NONE',
	PRIMARY KEY (id)
);